name: Pipeline
on: [push]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name: Super-linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.WF_TOKEN }}
          VALIDATE_BASH: false
          VALIDATE_CHECKOV: false
          FIX_MARKDOWN: true
          FIX_MARKDOWN_PRETTIER: true
          FIX_NATURAL_LANGUAGE: true
          FIX_SHELL_SHFMT: true
          FIX_YAML_PRETTIER: true
      - name: Commit and push linting fixes
        if: github.ref_name != 'main'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref_name }}
          commit_message: "chore: fix linting issues"
          commit_user_name: Wesley Scholl
          commit_user_email: wscholl@totalwine.com
      - id: automerge
        name: Merge 
        uses: "pascalgn/automerge-action@v0.16.3"
        env:
          GITHUB_TOKEN: "${{ secrets.WF_TOKEN }}"
